=== GyokayAli/University-Projects/UNI3/COMP1688 Service Oriented Web Applications/SOA based Freecycle Web App in PHP/level1/A single item by ID/XML_Document_Item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2016 sp1 (x64) (http://www.altova.com) by Gyokay Ali (GYOK ltd) -->
<!--W3C Schema generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="descr"/>
				<xs:element ref="post_date"/>
				<xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="member"/>
			</xs:sequence>
			<xs:attribute name="itemID" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="title" type="xs:string"/>
	<xs:element name="descr" type="xs:string"/>
	<xs:element name="post_date" type="xs:string"/>
	<xs:element name="image">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="imgID" type="xs:ID" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="member">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="full_name"/>
				<xs:element ref="postcode"/>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="contact_number" minOccurs="0"/>
					<xs:element ref="email" minOccurs="0"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="memID" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="full_name" type="xs:string"/>
	<xs:element name="postcode" type="xs:string"/>
	<xs:element name="contact_number" type="xs:string"/>
	<xs:element name="email" type="xs:string"/>
</xs:schema>

=== GyokayAli/University-Projects/UNI3/COMP1688 Service Oriented Web Applications/SOA based Freecycle Web App in PHP/level1/A single item by ID/XML_Document_Item.xml
<?xml version="1.0" encoding="UTF-8"?>
<item itemID="lew-item1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="\\stu-storage2\user-area\3\ag306\Desktop\COMP1688 SOWA\level 1\A single item by ID\XML_Document_Item.xsd">
	<title>Free toaster</title>
	<descr>New toaster. Never been used.</descr>
	<post_date>24/02/2016</post_date>
	<image imgID="lew-img1">toaster</image>
	<member memID="lew-0001">
		<full_name>John Doe</full_name>
		<postcode>SE18 5HF</postcode>
		<contact_number>0758856673</contact_number>
		<email>dj306@gre.ac.uk</email>
	</member>
</item>
